plugins {
    id 'java'
    id 'application'
    id 'idea'
}

run {
    standardInput = System.in
}

repositories {
    mavenCentral()
}

application {
    mainClass  = 'Main'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

compileJava.options.encoding = 'UTF-8'

dependencies {
    implementation 'tools.jackson.core:jackson-databind:3.1.2'
}

task hello {
    doLast {
        println 'Hello Gradle'
    }
}
